name: Publish frontend

on:
  push:
    branches:
      - develop
      - master

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.GH_OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node requirements
        run: npm i

      - name: Install Python requirements
        run: pip install -r requirements.txt

      - name: Build and publish
        env:
          PUBLISH_DOCS_USERNAME: ${{ vars.PUBLISH_DOCS_USERNAME }}
          PUBLISH_DOCS_PASSWORD: ${{ secrets.PUBLISH_DOCS_PASSWORD }}
        run: |
          SIMPLE_REF=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
          npm run publish-${SIMPLE_REF}
